import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  beehiveSidebar: [{ type: "autogenerated", dirName: "beehive" }],
};

export default sidebars;